chore(deps): update all dependencies (#1634)
* chore(deps): update all dependencies

* update dependencies

* migration to postgres v17 data

* revert to fastify v4
いくつかのプラグインはまだ Fastify v5 に対応していないため:

- https://github.com/ShogunPanda/fastify-http-errors-enhanced/issues/10
- https://github.com/nearform/fastify-auth0-verify/issues/366
- https://github.com/nearform/fastify-jwt-jwks/issues/26

* regenerate readme

* fix: error TS2783: 'kty' is specified more than once, so this usage will be overwritten.

* remove note

* test(registry): e2e セットアップファイルのスコープを修正 (#1582)

* test(registry): 並列実行対策

* globalSetupを失敗させないためにAdminDelete.runが例外を返さないようにする (#1600)

* fix: @oclif/plugin-pluginsを追加

* fix: AdminDelete.runが例外を返さないようにする

* chore: plugin-pluginsは不要

* fix: backout changes of pnpm-lock.yaml

* chore: AdminDelete.run()が例外を返さないようにする理由をコメント

---------

Co-authored-by: Shuuichirou Murata <31531654+mrt0a@users.noreply.github.com>

* revert to @playwright/test v1.44
Playwright stuck at about:blank instead of opening the test page
https://github.com/microsoft/playwright/issues/31050#issuecomment-2341861456

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Kohei Watanabe <nebel@fogtype.com>
Co-authored-by: somay <somay@users.noreply.github.com>
Co-authored-by: Shuuichirou Murata <31531654+mrt0a@users.noreply.github.com>