fix(deps): update all dependencies (#1989)
* fix(deps): update all dependencies

* remove deprecated @types/eslint__js dependency

* eslint --fix

* update dependencies to latest versions

* update to WordPress 6.7.2 with PHP 8.3

* update composer dependencies to latest versions

* tailwindcss v3 に戻す
#1991

* update README.md

* package.json に @eslint/js を追加

* remove unused '@ts-expect-error' directive

* fixed type error: add kty

* fixed type-error verifyIntegrity()

* fixed type-error: HttpResponse 生成プロセスを修正

* jose generateKeyPair に extractable オプションを追加

```
TypeError: non-extractable CryptoKey cannot be exported as a JWK
```

* build: vite:import-analysis でのエラーの回避

ssr オプションを追加し、各 vitest.config.ts の resolve 設定を更新

* "charset=UTF-8" -> "charset=utf-8" に変更されたが、そもそもチェック不要

refactor: use lowercase for charset
https://github.com/fastify/fastify-static/releases/tag/v8.0.3

* 非推奨になっているため UserConfig -> ViteUserConfig 型を使用するように修正

* 使用されていない conditions の削除

* 使用されていない vite.config.js を削除

* Revert "使用されていない conditions の削除"

This reverts commit 283c2dd0afb9788fe9f23bec958d35042b3477db.

* Revert "使用されていない vite.config.js を削除"

This reverts commit d766edd2630f9fa8d26d9034d0674002ad1b3ded.

* vite.config.js の型チェック有効化

* use defaultClientConditions

* v0.1.5

* v0.1.6-alpha.0

* remove deprecated @types/dompurify dependency

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: Kohei Watanabe <nebel@fogtype.com>
Co-authored-by: knokmki612 <knokmki612@users.noreply.github.com>